---
- name: Create override directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755

- name: Create configuration directory
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: Docker DNS configuration
  set_fact:
    docker_dns: "{{ ansible_dns.nameservers + docker_dns }}"
  when: docker_dns_add_local == True

- name: Add Docker configuration.
  template:
    src: 'daemon.json.j2'
    dest: '/etc/docker/daemon.json'
    owner: root
    group: root
    mode: 0644

- name: Add Docker systemd override.
  template:
    src: 'override.conf.j2'
    dest: '/etc/systemd/system/docker.service.d/override.conf'
    owner: root
    group: root
    mode: 0644

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add ansible to the docker group
  user:
    name: ansible
    groups: docker
    append: "yes"
