---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntuapp
    image: s3than/systemd-ubuntu:latest
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /run
      - /run/lock
    security_opts:
      - "seccomp:unconfined"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        docker_storage_driver: 'vfs'
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: flake8
